name: Deploy to server Laravel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.2.2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.MAIN_SECRETS_KEY }}
          REMOTE_HOST: 5.187.2.229
          REMOTE_USER: root
          source: "/"
          target: "/home/web/citydeft.com/public_html/deft-group"